### ISSUE TITLE
Wire stubs found in PCB design

### ISSUE THREAD

**Issue by darraghbr** [tetrabiodistributed/project-tetra#151]
Upon doing a DRC check the PCB has some curious wire stubs that don’t appear to be intentional, they should be replaced with polygon, this is probably not critical.

**Comment by mechatroniks-git** [comment]
I see 6 wire stub warnings, some in the GND plane get covered by GND polygon. None are an issue, but certainly worth cleaning up when fixing the other errors.

**Comment by hydronics2** [comment]
I tried deleting the wire stubs and I get air-wire warnings (un-routed
traces). This happens to me from time to time when I'm routing and
rerouting work between revisions... finicky Ealge thing... I'm not sure how
to get rid of the wire-stubs and because air-wire warnings are worse than
wire-stub warnings I'm inclined to leave them. If anyone can get rid of the
wire stubs, please go ahead.

**Comment by darraghbr** [comment]
Issue resolved by #152
