### ISSUE TITLE
A-TET-001005 - Add wires to assembly

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/project-tetra#96]
Need to add power and ground wires to the assembly. These typically come with the RPi display, but they need to be added as a component (virtual or modeled) and noted they need to be modified

**Comment by Burhan-Q** [comment]
Added virtual (empty) components to assembly, moving ticket to Review

**Comment by mechatroniks-git** [comment]
Try to use the existing nomenclature to avoid confusion during assembly:
![image](https://user-images.githubusercontent.com/57600622/88409083-51836280-cd89-11ea-89e9-3d5672033bb3.png)

![image](https://user-images.githubusercontent.com/57600622/88409213-80013d80-cd89-11ea-9775-369bcec2de0a.png)

**Comment by Burhan-Q** [comment]
@mechatroniks-git, Understood I will make these changes. The wires appeared to be grounding wires in the photos/videos posted but I did not look up they're purpose, and thought with respect to the BOM the wires would not need color specification.

Once changes are complete, should the Revision Number for the assembly be updated due to the addition of the virtual components?

**Comment by mechatroniks-git** [comment]
This would be a drawing revision from - to A. The assembly didn't change, just a documentation change.

**Comment by Burhan-Q** [comment]
Understood. Changes have been made. Please close if approved

**Comment by mmroden** [comment]
Jamie will do final approval

**Comment by Judoguy12** [comment]
Approved 28/07/2020

**Comment by Burhan-Q** [comment]
Issue can be closed when #80 is complete and ready for pull request
